spd: Fix the check on the tmux executable.

diff --git a/spd b/spd
--- a/spd
+++ b/spd
@@ -31,8 +31,8 @@ ERROR_PANE_MODE=4
 ERROR_PANE_KILL=5
 # - The requested number of panes is smaller than P*Q
 ERROR_PANE_NUMBER=6
-# - The tmux command is incorrect
-ERROR_TMUX_CMD=7
+# - The tmux executable is incorrect
+ERROR_TMUX_EXEC=7
 # - The creation of the user directory
 ERROR_USER_DIR=10
 # - The creation of the pipe directory
@@ -156,15 +156,16 @@ main() {
 
   # Define tmux command line, appending a socket if requested.
   TMUX_EXEC="${TMUX_BIN:+${TMUX_BIN}/}tmux"
+
+  # check the tmux executable is correct.
+  decho "TMUX_EXEC: ${TMUX_EXEC}"
+  ${TMUX_EXEC} ls 2>&1 >/dev/null \
+    || error "Cannot use tmux executable ${TMUX_EXEC}" ${ERROR_TMUX_EXEC}
+
   TMUX_CMD=${TMUX_EXEC}
   if [ ${SPD_TMUX_USE_USER_SOCKET} -eq ${TRUE} ]; then
     TMUX_CMD+=" -S ${SPD_USER_TMUX_TMPDIR}"
   fi
-
-  # check the tmux command is correct.
-  decho "TMUX_CMD: ${TMUX_CMD}"
-  ${TMUX_CMD} ls 2>&1 \
-    || error "Cannot use tmux command ${TMUX_CMD}" ${ERROR_TMUX_CMD}
 
   # Extract tmux info using TMUX_CMD:
   #   - Current session name
@@ -436,7 +437,7 @@ tmux_cmd_sent() {
   local desc="This function prints message related to tmux commands sent."
   local msg=$*
 
-  echo -e "${CYAN}${msg}${NOFORMAT}"
+  decho -e "${CYAN}${msg}${NOFORMAT}"
 }
 
 # Concat elements of an array
